

version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: systeminfo
      
      - run:
          name: "Login to Docker Hub"
          shell: powershell.exe
          command: docker login -u "pusamsaikumar302@gmail.com" -p "VK_SE5kK*Gjb2F&"
            
      - run:
          name: "Build Docker Image"
          shell: powershell.exe
          command: |
            docker build -t pusamsai/circle-test-app:latest -f ./Dockerfile .
      - run:
          name: "Push Docker Image"
          shell: powershell.exe
          command: |
            docker push pusamsai/circle-test-app:latest

