version: 2.1

jobs:
  build:
    docker:
      - image: circleci/dotnet:6.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Install Docker client
          command: |
            apt-get update && apt-get install -y docker.io
      - run:
          name: Build Docker image
          command: docker build -t myapi:latest .
      - run:
          name: Log in to Docker Hub
          command: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - run:
          name: Push Docker image to Docker Hub
          command: docker tag googlecloudapp:latest pusamsai/circle-test-app:latest && docker push pusamsai/circle-test-app:latest

         


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
