version: 2.1

executors:
  windows:
    machine:
      image: windows-server-2019

jobs:
  build_and_push:
    executor: windows
    steps:
      - checkout

      - run:
          name: Install Docker
          command: |
            Install-PackageProvider -Name NuGet -Force
            Install-Module -Name DockerMsftProvider -Repository PSGallery -Force
            Install-Package -Name docker -ProviderName DockerMsftProvider -Force
            Start-Service Docker

      - run:
          name: Verify Docker Installation
          command: docker --version

      - run:
          name: Build Docker Image
          command: docker build -t pusamsai/circle-test-app:latest -f GoogleCloudApp/Dockerfile .

      - run:
          name: Login to Docker Hub
          command: |
            docker login -u pusamsaikumar302@gmail.com -p VK_SE5kK*Gjb2F&

      - run:
          name: Tag Docker Image
          command: docker tag googlecloudapp pusamsai/circle-test-app:latest

      - run:
          name: Push Docker Image to Docker Hub
          command: docker push pusamsai/circle-test-app:latest

workflows:
  version: 2
  build_and_push:
    jobs:
      - build_and_push
