# Use the official ASP.NET Core runtime as a base image
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

# Use the official ASP.NET Core SDK image for building the application
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["GoogleCloudApp/GoogleCloudApp.csproj", "GoogleCloudApp/"]
RUN dotnet restore "GoogleCloudApp/GoogleCloudApp.csproj"
COPY . .
WORKDIR "/src/GoogleCloudApp"
RUN dotnet build "GoogleCloudApp.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "GoogleCloudApp.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "GoogleCloudApp.dll"]
